version: '3.9'

services:
  rabbitmq-server:
    container_name: rabbitmq-server
    image: rabbitmq:3.12.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data: